name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Nurrakha
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
              dist/github-pacman.svg?color_snake=yellow&color_dots=#FFD700,#00BFFF,#FF6347,#FFA500&color_empty=#161B22&color_food=#00BFFF

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
